BASE_DIR = $(HOME)/arduino

# Adjust the next line when copy/pasting to a different directory
PROJECT_DIR = $(BASE_DIR)/signalboxes/kelberg

include $(BASE_DIR)/base.mk
# Board overrides for the base config
BOARD_TAG         = mega
BOARD_SUB         = atmega2560


OBJDIR = $(PROJECT_DIR)/bin
include $(ARDMK_DIR)/Arduino.mk
