BASE_DIR = $(HOME)/arduino
include $(BASE_DIR)/base.mk

PROJECT_DIR = $(BASE_DIR)/current-test-program
OBJDIR            = $(PROJECT_DIR)/bin

### path to Arduino.mk, inside the ARDMK_DIR, don't touch.
include $(ARDMK_DIR)/Arduino.mk
