BASE_DIR = $(HOME)/arduino

# Adjust the next line when copy/pasting to a different directory
PROJECT_DIR = $(BASE_DIR)/signals/mayen_e

include $(BASE_DIR)/base.mk
OBJDIR = $(PROJECT_DIR)/bin
include $(ARDMK_DIR)/Arduino.mk
